syntax = "proto3";
package app.player;
import "entity/friend.proto";
import "entity/invitation.proto";
import "entity/limitation.proto";
import "entity/notification.proto";
import "entity/player.proto";

message WhoamiRequest {
}
message WhoamiResponse {
  string player_id = 1;
}
message GetPlayerDataRequest {
}
message GetPlayerDataResponse {
  .entity.PlayerData player_data = 1;
  .entity.Notification notification = 2;
  .entity.Limitation limitation = 3;
  .entity.Friends friends = 4;
  .entity.Invitation invitation = 5;
  int64 accountid = 6;
  int64 world_room_id = 7;
  string iap_google_account_binding = 8;
  string iap_apple_account_binding = 9;
}
service PlayerService {
  rpc Whoami (.app.player.WhoamiRequest) returns (.app.player.WhoamiResponse);
  rpc GetPlayerData (.app.player.GetPlayerDataRequest) returns (.app.player.GetPlayerDataResponse);
}
