syntax = "proto3";
package app.playerlogin;
import "entity/method_options/method_options.proto";
message GetServerListRequest {}
message ServerInfo {
  string name = 1;
  string cdn_root = 2;
  string api_server_root = 3;
  string chat_server_root = 4;
  string at_server_root = 5;
  string live_server = 6;
  string display_name = 7;
  string area_id = 8;
  string age_icon_sprite_name = 9;
}
message GetServerListResponse { repeated ServerInfo servers = 1; }
service PlayerLoginService {
  rpc GetServerList(GetServerListRequest) returns (GetServerListResponse) { option (entity.method_options.skip_authentication) = true; }
}
